# Generated by Django 6.1 on 2026-08-13 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effiadmi', '0003_notificaciones_productos_proveedores_reportes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='movimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'ENTRADA'), ('salida', 'SALIDA'), ('ajuste', 'AJUSTE')], max_length=20)),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, default='')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='effiadmi.productos')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='effiadmi.usuario')),
            ],
        ),
    ]
