# Generated by Django 6.1 on 2026-08-20 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('effiadmi', '0005_branch_product_inventory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reportes',
        ),
    ]
