# Generated by Django 6.0.7 on 2026-08-27

import django.db.models.deletion
from django.db import migrations, models


def crear_categorias_y_vincular(apps, schema_editor):
    Product = apps.get_model("effiadmi", "Product")
    Categoria = apps.get_model("effiadmi", "Categoria")

    mapeo = {}
    for prod in Product.objects.exclude(categoria_legado="").exclude(categoria_legado__isnull=True).iterator():
        nombre = str(prod.categoria_legado).strip()
        if not nombre:
            continue
        if nombre not in mapeo:
            cat, _ = Categoria.objects.get_or_create(nombre=nombre)
            mapeo[nombre] = cat
        prod.categoria = mapeo[nombre]
        prod.save(update_fields=["categoria"])


def deshacer(apps, schema_editor):
    Product = apps.get_model("effiadmi", "Product")
    for prod in Product.objects.exclude(categoria__isnull=True).iterator():
        prod.categoria_legado = prod.categoria.nombre
        prod.save(update_fields=["categoria_legado"])


class Migration(migrations.Migration):

    dependencies = [
        ('effiadmi', '0005_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='effiadmi.categoria'),
        ),
        migrations.RunPython(crear_categorias_y_vincular, deshacer),
        migrations.RemoveField(
            model_name='product',
            name='categoria_legado',
        ),
    ]
