# Generated by Django 6.0.7 on 2026-09-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effiadmi', '0006_product_categoria_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='enlace',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
