# Generated by Django 6.1 on 2026-09-18 18:27

import django.db.models.deletion
import effiadmi.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effiadmi', '0007_notificacion_enlace'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorreoEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.EmailField(db_index=True, max_length=254)),
                ('asunto', models.CharField(max_length=200)),
                ('cuerpo', models.TextField()),
                ('exitoso', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, default='')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Correo Enviado',
                'verbose_name_plural': 'Correos Enviados',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='FacturaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, default='', max_length=80)),
                ('fecha', models.DateField(db_index=True)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('archivo', models.FileField(blank=True, null=True, upload_to=effiadmi.models._ruta_factura_compra)),
                ('notas', models.TextField(blank=True, default='')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_compra', to='effiadmi.proveedor')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Factura de Compra',
                'verbose_name_plural': 'Facturas de Compra',
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['-fecha'], name='effiadmi_fa_fecha_bfe1d5_idx')],
            },
        ),
    ]
