# Generated by Django 6.1 on 2026-09-18 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def asignar_mensajes_antiguos(apps, schema_editor):
    """Agrupa los chats existentes (sin conversacion) en una conversacion por usuario."""
    User = apps.get_model(settings.AUTH_USER_MODEL)
    Conversacion = apps.get_model("effiadmi", "Conversacion")
    ChatHistorial = apps.get_model("effiadmi", "ChatHistorial")

    for usuario in User.objects.all():
        sin_grupo = ChatHistorial.objects.filter(usuario=usuario, conversacion__isnull=True)
        if not sin_grupo.exists():
            continue
        conversacion = Conversacion.objects.create(usuario=usuario, titulo="Historial")
        sin_grupo.update(conversacion=conversacion)


class Migration(migrations.Migration):

    dependencies = [
        ('effiadmi', '0008_correoenviado_facturacompra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Nueva conversacion', max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversacion',
                'verbose_name_plural': 'Conversaciones',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.AddField(
            model_name='chathistorial',
            name='conversacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='effiadmi.conversacion'),
        ),
        migrations.RunPython(asignar_mensajes_antiguos, migrations.RunPython.noop),
    ]
